### ISSUE TITLE
/mcontext bug

### ISSUE THREAD

**Issue by mbusigin** [Arbaaz-Mahmood/cognosis-II#1]
Running agent Apex for session ec3897ae-8283-44b5-90f6-e5a3bd68db2c_Apex with message: /mcontext *dataset.ts
TypeError: str.replace is not a function
    at Apex.escapeSpecialChars (/Users/mbusigin/cognosis-II/backend/agents/autoload/apex.ts:23:20)
    at Apex.convertToDSL (/Users/mbusigin/cognosis-II/backend/agents/autoload/apex.ts:49:51)
    at Apex.<anonymous> (/Users/mbusigin/cognosis-II/backend/agents/autoload/apex.ts:125:32)
    at Generator.next (<anonymous>)
    at /Users/mbusigin/cognosis-II/backend/agents/autoload/apex.ts:8:71
    at new Promise (<anonymous>)
    at __awaiter (/Users/mbusigin/cognosis-II/backend/agents/autoload/apex.ts:4:12)
    at Apex.run (/Users/mbusigin/cognosis-II/backend/agents/autoload/apex.ts:84:16)
    at /Users/mbusigin/cognosis-II/backend/index.ts:94:20
    at Generator.next (<anonymous>)

**Comment by mbusigin** [comment]
Sorry @Arbaaz-Mahmood I thought this was yours lol

**Comment by mbusigin** [comment]
Fixed
